#!/bin/bash

################# Functions ##############
checkPackages() { # check if YAD is installed
    echo "Checking packages..."
    everything_installed=false
    missing_packages=""

    yad_installed=$(which yad)
    is_yad_installed=${yad_installed:0:1}
    # echo $is_yad_installed

    if [ "$is_yad_installed" != "/" ]; then
        xterm -T YadBomb -e "/bin/bash yad_installer.sh"
    fi
}

exploit() {
    arch=$(uname -m)

    if [[ $arch == "x86_64" ]]; then
        bluebomb_file="bluebomb-x64"
    else
        bluebomb_file="bluebomb-x86"
    fi

    cd bluebomb1.5
    chmod +x $bluebomb_file
    echo $bluebomb_file

    options=""
    cd stage0
    for file in *.bin; do
        if [[ $file != "RQFE6U.bin" ]]; then
            options="${options}${file%.*}!"
        fi
    done
    cd .. # bluebomb

    options=${options%?} # cuts out the last char (an extra '!' sign)
    # echo $options

    form_data=$(yad --title "YadBomb" \
    --text="    Choose the filename that contains your Device, System Menu, and Region" \
    --form \
    --field="   Choose your console and System Menu: ":CB \
    "$options" \
    --field="Use external bluetooth adapter":CHK \
    --button="OK":0) \
    # --button="USA":1

    choice=$?

    bin_file=$(echo $form_data | awk 'BEGIN {FS="|"} {print $1}') # filename without extension
    binfile="${bin_file}.bin" # filename with extension

    external=$(echo $form_data | awk 'BEGIN {FS="|"} {print $2}')

    if [ $external = TRUE ]; then
        hci_device="1"
    else
        hci_device=""
    fi

    echo "chosen \"$bin_file\""
    echo "will use \"$binfile\""

    echo "HCI device: \"${hci_device}\""

    yad --title "YadBomb" \
    --text="    next you'll be redirected to a terminal

    if it displays \"waiting to accept\", you're almost done, just follow the steps below (after clicked OK button):

    1) Download HackMii Installer from this link: https://bootmii.org/download/

    2) Copy everything from inside \"HackMii Installer\" to the root of your usb stick

    3) Plug the usb stick to your console

    4) Turn on your console till \"Health and Safety\" screen

    5) Remove the batteries from all wiimotes

    6) Make sure your console is close to your bluetooth adapter, you may have to move it closer to get it in range, this will depend on your adapter

    7) Press the SYNC button on your console multiple times till the computer shows \"Got connection handle: #\".
    You may have to press it (SYNC) several times in order to get such a message (Got connection handle).

    Then, the console should boot the Hackmii installer after a few seconds.
    Once you are in the Hackmii installer, put the batteries back into the Wiimote and install the Homebrew Channel.


    When you're ready, click the OK button below" \
    --selectable-labels \
    --button="OK":0 \
    --fixed \
    --center

    # echo $choice

    clear

    if [ $choice -eq 1 ]
        then
            # echo "Exploiting for USA console..."
            # sudo ./bluebomb-x86 ./stage0/MINI_SM_NTSC.bin stage1.bin
            # xterm -T YadBomb -e /bin/bash -c "sudo systemctl disable --now bluetooth && echo Exploiting for $bin_file... ; sudo ./${bluebomb_file} ./stage0/$binfile stage1.bin ; echo FINISHED, you can close this window now, HAVE FUN! ; bash"
            echo "Back to ComboBox screen"
            # xfce4-terminal -e 'bash --fullscreen -c "echo Exploiting for USA console... ; sudo ./bluebomb-x86 ./stage0/MINI_SM_NTSC.bin stage1.bin ; bash" -T YadBomb'
            # xfce4-terminal -e 'bash -c "sudo ./bluebomb-x86 ./stage0/MINI_SM_NTSC.bin stage1.bin ; bash" -T YadBomb'

    elif [ $choice -eq 0 ]
        then
            # echo Exploiting for PAL console...
            # sudo ./bluebomb-x86 ./stage0/MINI_SM_PAL.bin stage1.bin

            xterm -T YadBomb -e /bin/bash -c "echo Exploiting for $bin_file... && sudo systemctl disable --now bluetooth && sudo ./${bluebomb_file} ${hci_device} ./stage0/$binfile stage1.bin ; echo FINISHED, press ENTER to close and HAVE FUN! ; read enter"
            # xfce4-terminal -e 'bash --fullscreen -c "echo Exploiting for PAL console... ; sudo ./bluebomb-x86 ./stage0/MINI_SM_PAL.bin stage1.bin ; bash" -T YadBomb'
    fi

}




################# Main ###############
checkPackages

yad --title "YadBomb" \
--text="    This wizard will help you installing bluebomb, a software developed by Fullmetal5

    This wizard will NOT install any cIOS, only the Homebrew Channel

    Bluebomb on github:
    https://github.com/Fullmetal5/bluebomb

    Do you want to proceed?" \
--selectable-labels \
--button="No":0 \
--button="Yes":1

choice=$?

# echo $choice

if [ $choice -eq 1 ]
    then
        exploit
        # checkBluetoothSettings
fi
